In [72]:
import numpy as np
# import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

In [73]:
from numpy.random import seed
seed(1)

In [74]:
dataset=pd.read_csv("Data/testset.csv")
dataset

datetime_utc          _conds  _dewptm  ...  _wgustm  _windchillm  _wspdm
0      19961101-11:00           Smoke      9.0  ...      NaN          NaN     7.4
1      19961101-12:00           Smoke     10.0  ...      NaN          NaN     NaN
2      19961101-13:00           Smoke     11.0  ...      NaN          NaN     NaN
3      19961101-14:00           Smoke     10.0  ...      NaN          NaN     NaN
4      19961101-16:00           Smoke     11.0  ...      NaN          NaN     0.0
...               ...             ...      ...  ...      ...          ...     ...
99565  20161231-12:00   Partly Cloudy     15.0  ...      NaN          NaN     7.4
99566  20161231-13:00   Partly Cloudy     16.0  ...      NaN          NaN     3.7
99567  20161231-15:00             NaN     13.0  ...      NaN          NaN    59.3
99568  20161231-18:00  Patches of Fog     12.0  ...      NaN          NaN     0.0
99569  20161231-21:00  Patches of Fog     12.0  ...      NaN          NaN     0.0

[99570 rows x 20 columns]

In [75]:
dataset.columns=dataset.columns.str.replace("_","")
dataset.columns=dataset.columns.str.replace(" ","")
dataset.columns

Index(['datetimeutc', 'conds', 'dewptm', 'fog', 'hail', 'heatindexm', 'hum',
       'precipm', 'pressurem', 'rain', 'snow', 'tempm', 'thunder', 'tornado',
       'vism', 'wdird', 'wdire', 'wgustm', 'windchillm', 'wspdm'],
      dtype='object')

In [76]:
dataset.drop(columns=["conds","dewptm","fog","hail","heatindexm","precipm","rain","snow","thunder","tornado","vism","wdird","wdire","wgustm","windchillm"],inplace=True,axis=1)
dataset

datetimeutc    hum  pressurem  tempm  wspdm
0      19961101-11:00   27.0     1010.0   30.0    7.4
1      19961101-12:00   32.0    -9999.0   28.0    NaN
2      19961101-13:00   44.0    -9999.0   24.0    NaN
3      19961101-14:00   41.0     1010.0   24.0    NaN
4      19961101-16:00   47.0     1011.0   23.0    0.0
...               ...    ...        ...    ...    ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4
99566  20161231-13:00  100.0     1014.0   16.0    3.7
99567  20161231-15:00    NaN     1016.0    NaN   59.3
99568  20161231-18:00  100.0     1016.0   12.0    0.0
99569  20161231-21:00   99.0     1016.0   12.0    0.0

[99570 rows x 5 columns]

In [77]:
dataset['pressurem'].replace('-9999.0',np.nan)
dataset.replace(0,np.nan)
dataset.isnull().sum()

datetimeutc       0
hum             756
pressurem       232
tempm           672
wspdm          2358
dtype: int64

In [78]:
dataset

datetimeutc    hum  pressurem  tempm  wspdm
0      19961101-11:00   27.0     1010.0   30.0    7.4
1      19961101-12:00   32.0    -9999.0   28.0    NaN
2      19961101-13:00   44.0    -9999.0   24.0    NaN
3      19961101-14:00   41.0     1010.0   24.0    NaN
4      19961101-16:00   47.0     1011.0   23.0    0.0
...               ...    ...        ...    ...    ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4
99566  20161231-13:00  100.0     1014.0   16.0    3.7
99567  20161231-15:00    NaN     1016.0    NaN   59.3
99568  20161231-18:00  100.0     1016.0   12.0    0.0
99569  20161231-21:00   99.0     1016.0   12.0    0.0

[99570 rows x 5 columns]

In [79]:
hum_median=dataset["hum"].median()
dataset["hum"].fillna(hum_median,inplace=True)
pressurem_median=dataset["pressurem"].median()
dataset["pressurem"].fillna(pressurem_median,inplace=True)
wspdm_median=dataset["wspdm"].median()
dataset["wspdm"].fillna(wspdm_median,inplace=True)
tempm_median=dataset["tempm"].median()
dataset["tempm"].fillna(tempm_median,inplace=True)

In [80]:
dataset.isnull().sum()

datetimeutc    0
hum            0
pressurem      0
tempm          0
wspdm          0
dtype: int64

In [81]:
dataset

datetimeutc    hum  pressurem  tempm  wspdm
0      19961101-11:00   27.0     1010.0   30.0    7.4
1      19961101-12:00   32.0    -9999.0   28.0    7.4
2      19961101-13:00   44.0    -9999.0   24.0    7.4
3      19961101-14:00   41.0     1010.0   24.0    7.4
4      19961101-16:00   47.0     1011.0   23.0    0.0
...               ...    ...        ...    ...    ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4
99566  20161231-13:00  100.0     1014.0   16.0    3.7
99567  20161231-15:00   58.0     1016.0   27.0   59.3
99568  20161231-18:00  100.0     1016.0   12.0    0.0
99569  20161231-21:00   99.0     1016.0   12.0    0.0

[99570 rows x 5 columns]

In [82]:
dataset["datetimeutc"]=pd.to_datetime(dataset["datetimeutc"])

In [83]:
dataset.set_index("datetimeutc",inplace=True)

In [84]:
dataset

hum  pressurem  tempm  wspdm
datetimeutc                                        
1996-11-01 11:00:00   27.0     1010.0   30.0    7.4
1996-11-01 12:00:00   32.0    -9999.0   28.0    7.4
1996-11-01 13:00:00   44.0    -9999.0   24.0    7.4
1996-11-01 14:00:00   41.0     1010.0   24.0    7.4
1996-11-01 16:00:00   47.0     1011.0   23.0    0.0
...                    ...        ...    ...    ...
2016-12-31 12:00:00   77.0     1015.0   18.0    7.4
2016-12-31 13:00:00  100.0     1014.0   16.0    3.7
2016-12-31 15:00:00   58.0     1016.0   27.0   59.3
2016-12-31 18:00:00  100.0     1016.0   12.0    0.0
2016-12-31 21:00:00   99.0     1016.0   12.0    0.0

[99570 rows x 4 columns]

In [85]:
dataset=dataset.resample("D").mean()
dataset

hum    pressurem      tempm      wspdm
datetimeutc                                              
1996-11-01   52.916667 -2659.666667  22.333333   6.166667
1996-11-02   48.625000  1009.833333  22.916667   7.950000
1996-11-03   55.958333  1010.500000  21.791667   5.020833
1996-11-04   48.055556  1011.333333  22.722222   2.266667
1996-11-05   29.400000  1011.800000  27.800000  10.020000
...                ...          ...        ...        ...
2016-12-27   67.550000  1017.200000  16.850000   8.335000
2016-12-28   68.043478  1015.565217  17.217391   3.547826
2016-12-29   87.857143  1016.904762  15.238095   6.000000
2016-12-30   89.666667  1017.904762  14.095238   6.266667
2016-12-31   85.550000  1016.100000  15.650000   7.325000

[7366 rows x 4 columns]

In [86]:
def extract_year(value):
  value=value.strftime('%Y-%m-%d')
  return (value[0:4])


def extract_month(value):
    value=value.strftime('%Y-%m-%d')
    return (value[4:6])

def extract_date(value):
    value=value.strftime('%Y-%m-%d')
    return (value[6:8])

In [87]:
dataset.reset_index(inplace=True)
dataset


datetimeutc        hum    pressurem      tempm      wspdm
0     1996-11-01  52.916667 -2659.666667  22.333333   6.166667
1     1996-11-02  48.625000  1009.833333  22.916667   7.950000
2     1996-11-03  55.958333  1010.500000  21.791667   5.020833
3     1996-11-04  48.055556  1011.333333  22.722222   2.266667
4     1996-11-05  29.400000  1011.800000  27.800000  10.020000
...          ...        ...          ...        ...        ...
7361  2016-12-27  67.550000  1017.200000  16.850000   8.335000
7362  2016-12-28  68.043478  1015.565217  17.217391   3.547826
7363  2016-12-29  87.857143  1016.904762  15.238095   6.000000
7364  2016-12-30  89.666667  1017.904762  14.095238   6.266667
7365  2016-12-31  85.550000  1016.100000  15.650000   7.325000

[7366 rows x 5 columns]

In [ ]:
dataset.year.value_counts()

2003    13186
2004     9151
2002     8503
2001     8403
2016     6634
1997     6513
1999     6300
2000     5391
1998     3579
2014     2973
2015     2936
2005     2920
2007     2865
2006     2858
2008     2857
2009     2851
2010     2768
2011     2738
2012     2438
2013     2428
1996     1278
Name: year, dtype: int64

In [ ]:
dataset.groupby("year").tempm.mean()

year
1996    16.658059
1997    24.477199
1998    24.872031
1999    27.333333
2000    23.884252
2001    25.599667
2002    26.487005
2003    26.182239
2004    26.010054
2005    24.720548
2006    25.455213
2007    24.813264
2008    24.527476
2009    25.358821
2010    25.559610
2011    24.968590
2012    25.028712
2013    24.690692
2014    25.184326
2015    25.148161
2016    27.314591
Name: tempm, dtype: float64

In [88]:
dataset['day'] = dataset['datetimeutc'].dt.day
dataset['month'] = dataset['datetimeutc'].dt.month
dataset['year'] = dataset['datetimeutc'].dt.year

In [89]:
dataset.isnull().sum()

datetimeutc      0
hum            141
pressurem      141
tempm          141
wspdm          141
day              0
month            0
year             0
dtype: int64

In [90]:
dataset.fillna(dataset.mean(),inplace=True)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  """Entry point for launching an IPython kernel.


In [91]:
dataset.isnull().sum()

datetimeutc    0
hum            0
pressurem      0
tempm          0
wspdm          0
day            0
month          0
year           0
dtype: int64

In [92]:
dataset_forest=dataset.drop(["datetimeutc"],axis=1)
dataset_forest

hum    pressurem      tempm      wspdm  day  month  year
0     52.916667 -2659.666667  22.333333   6.166667    1     11  1996
1     48.625000  1009.833333  22.916667   7.950000    2     11  1996
2     55.958333  1010.500000  21.791667   5.020833    3     11  1996
3     48.055556  1011.333333  22.722222   2.266667    4     11  1996
4     29.400000  1011.800000  27.800000  10.020000    5     11  1996
...         ...          ...        ...        ...  ...    ...   ...
7361  67.550000  1017.200000  16.850000   8.335000   27     12  2016
7362  68.043478  1015.565217  17.217391   3.547826   28     12  2016
7363  87.857143  1016.904762  15.238095   6.000000   29     12  2016
7364  89.666667  1017.904762  14.095238   6.266667   30     12  2016
7365  85.550000  1016.100000  15.650000   7.325000   31     12  2016

[7366 rows x 7 columns]

In [93]:
y=dataset_forest["tempm"]
y

0       22.333333
1       22.916667
2       21.791667
3       22.722222
4       27.800000
          ...    
7361    16.850000
7362    17.217391
7363    15.238095
7364    14.095238
7365    15.650000
Name: tempm, Length: 7366, dtype: float64

In [94]:
dataset_forest.drop("tempm",inplace=True,axis=1)

In [95]:
X=dataset_forest.iloc[:,:].values

In [96]:
X.shape

(7366, 6)

In [97]:
y=y.values


In [98]:
y.shape

(7366,)

In [99]:
# Train and Test Part

In [100]:
from sklearn.model_selection import train_test_split

In [101]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=0)

In [102]:
print("Shape of X_train", X_train.shape)
print("Shape of X_test", X_test.shape)
print("Shape of y_train", y_train.shape)
print("Shape of y_test", y_test.shape)

Shape of X_train (4935, 6)
Shape of X_test (2431, 6)
Shape of y_train (4935,)
Shape of y_test (2431,)


In [103]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
sc_Y=StandardScaler()
X_train=sc_X.fit_transform(X_train)
y_train=np.array(y_train).reshape(-1,1)
y_train=sc_Y.fit_transform(y_train)
# y_train=np.array(y_train).reshape(-1,1)

In [104]:
#Create Model
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor(random_state=0)

In [105]:
model.fit(X_train,y_train.ravel())

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [106]:
X_test=sc_X.fit_transform(X_test)

In [107]:
y_pred=model.predict(X_test)

In [108]:
y_pred=sc_Y.inverse_transform(y_pred)
y_pred

array([29.375     , 32.83333333, 25.18181818, ..., 19.91666667,
       33.25      , 18.        ])

In [109]:
y_test

array([28.875     , 32.5       , 24.75      , ..., 19.52173913,
       32.875     , 14.71428571])

In [111]:
# Accuracy
from sklearn.metrics import mean_squared_error, mean_absolute_error
mse=mean_squared_error(y_test,y_pred,squared=False)
mae=mean_absolute_error(y_test,y_pred)
print(f'{mse} {mae}')

3.414786719111552 2.472285887867981


In [112]:
y_pred.size

2431

In [ ]:
avg=0
for i in range(0,y_pred.size):
    avg+=abs(y_pred[i]-y_test[i])
avg

18268.928548003103

In [ ]:
avg/(y_pred.size)

1.8347824192028828

In [ ]:
df = pd.DataFrame({'Real Values':y_test.reshape(-1), 'Predicted Values':y_pred.reshape(-1)})
df

Real Values  Predicted Values
0            32.0              31.0
1            34.0              31.0
2            16.0              13.0
3            19.0              17.0
4            28.0              22.0
...           ...               ...
9952         27.0              23.0
9953         37.0              30.0
9954         32.0              27.0
9955         12.0              12.0
9956         25.0              25.0

[9957 rows x 2 columns]

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(y_test,y_pred)

7.913564634368969

In [ ]:
mean_absolute_error(y_test,y_pred)

1.8347824192028828

In [ ]:
y

array([30., 28., 24., ..., 27., 12., 12.])

In [ ]:
y>50

array([False, False, False, ..., False, False, False])

In [ ]:
d=y>50

In [ ]:
d.size

99570

In [ ]:
for i in range(0,d.size):
    if(d[i]==True):
        print("here")

here
here
here
here


In [113]:
test=pd.read_csv("archive/DailyDelhiClimateTest.csv")

In [114]:
test

date   meantemp   humidity  wind_speed  meanpressure
0    2017-01-01  15.913043  85.869565    2.743478     59.000000
1    2017-01-02  18.500000  77.222222    2.894444   1018.277778
2    2017-01-03  17.111111  81.888889    4.016667   1018.333333
3    2017-01-04  18.700000  70.050000    4.545000   1015.700000
4    2017-01-05  18.388889  74.944444    3.300000   1014.333333
..          ...        ...        ...         ...           ...
109  2017-04-20  34.500000  27.500000    5.562500    998.625000
110  2017-04-21  34.250000  39.375000    6.962500    999.875000
111  2017-04-22  32.900000  40.900000    8.890000   1001.600000
112  2017-04-23  32.875000  27.500000    9.962500   1002.125000
113  2017-04-24  32.000000  27.142857   12.157143   1004.142857

[114 rows x 5 columns]

In [115]:
def extract_year(value):
    return (value[0:4])

In [116]:
def extract_month(value):
    return (value[5:7])

In [117]:
def extract_date(value):
    return (value[8:10])

In [118]:
test["year"]=test["date"].apply(lambda x : extract_year(x))

In [119]:
test["month"]=test["date"].apply(lambda x : extract_month(x))

In [120]:
test["dat"]=test["date"].apply(lambda x : extract_date(x))

In [121]:
test

date   meantemp   humidity  wind_speed  meanpressure  year month dat
0    2017-01-01  15.913043  85.869565    2.743478     59.000000  2017    01  01
1    2017-01-02  18.500000  77.222222    2.894444   1018.277778  2017    01  02
2    2017-01-03  17.111111  81.888889    4.016667   1018.333333  2017    01  03
3    2017-01-04  18.700000  70.050000    4.545000   1015.700000  2017    01  04
4    2017-01-05  18.388889  74.944444    3.300000   1014.333333  2017    01  05
..          ...        ...        ...         ...           ...   ...   ...  ..
109  2017-04-20  34.500000  27.500000    5.562500    998.625000  2017    04  20
110  2017-04-21  34.250000  39.375000    6.962500    999.875000  2017    04  21
111  2017-04-22  32.900000  40.900000    8.890000   1001.600000  2017    04  22
112  2017-04-23  32.875000  27.500000    9.962500   1002.125000  2017    04  23
113  2017-04-24  32.000000  27.142857   12.157143   1004.142857  2017    04  24

[114 rows x 8 columns]

In [122]:
test.dtypes

date             object
meantemp        float64
humidity        float64
wind_speed      float64
meanpressure    float64
year             object
month            object
dat              object
dtype: object

In [123]:
pred=test['meantemp']
pred

0      15.913043
1      18.500000
2      17.111111
3      18.700000
4      18.388889
         ...    
109    34.500000
110    34.250000
111    32.900000
112    32.875000
113    32.000000
Name: meantemp, Length: 114, dtype: float64

In [124]:
test.drop('meantemp',inplace=True,axis=1)
test.drop('date',inplace=True,axis=1)
# test.drop('meanpressure',inplace=True,axis=1)
test

humidity  wind_speed  meanpressure  year month dat
0    85.869565    2.743478     59.000000  2017    01  01
1    77.222222    2.894444   1018.277778  2017    01  02
2    81.888889    4.016667   1018.333333  2017    01  03
3    70.050000    4.545000   1015.700000  2017    01  04
4    74.944444    3.300000   1014.333333  2017    01  05
..         ...         ...           ...   ...   ...  ..
109  27.500000    5.562500    998.625000  2017    04  20
110  39.375000    6.962500    999.875000  2017    04  21
111  40.900000    8.890000   1001.600000  2017    04  22
112  27.500000    9.962500   1002.125000  2017    04  23
113  27.142857   12.157143   1004.142857  2017    04  24

[114 rows x 6 columns]

In [125]:
X=test.iloc[:,:].values
X.shape

(114, 6)

In [126]:
X=sc_X.fit_transform(X)

In [127]:
pred=pred.values
pred.shape

(114,)

In [128]:
y_pred=model.predict(X)

In [129]:
y_pred=sc_Y.inverse_transform(y_pred)
y_pred

array([16.92307692, 16.11111111, 16.11111111, 16.11111111, 16.11111111,
       14.75      , 16.29166667, 18.16666667, 18.16666667, 18.5       ,
       18.5       , 18.125     , 18.125     , 18.125     , 18.125     ,
       18.5       , 18.16666667, 18.16666667, 15.        , 14.875     ,
       14.875     , 18.125     , 18.125     , 18.125     , 15.125     ,
       11.08333333, 13.5       , 11.5       , 13.5       , 18.16666667,
       18.125     , 24.13043478, 26.43478261, 24.13043478, 26.22222222,
       24.75      , 26.22222222, 26.125     , 26.125     , 26.125     ,
       34.58333333, 26.125     , 24.13043478, 26.43478261, 26.43478261,
       26.43478261, 34.58333333, 34.58333333, 24.13043478, 26.125     ,
       26.125     , 34.58333333, 32.83333333, 34.58333333, 34.58333333,
       34.58333333, 34.58333333, 31.52631579, 31.52631579, 31.5       ,
       31.5       , 31.5       , 31.56521739, 25.15093453, 25.15093453,
       33.08333333, 34.58333333, 31.68181818, 34.58333333, 31.75

In [130]:
pred

array([15.91304348, 18.5       , 17.11111111, 18.7       , 18.38888889,
       19.31818182, 14.70833333, 15.68421053, 14.57142857, 12.11111111,
       11.        , 11.78947368, 13.23529412, 13.2       , 16.43478261,
       14.65      , 11.72222222, 13.04166667, 14.61904762, 15.26315789,
       15.39130435, 18.44      , 18.11764706, 18.34782609, 21.        ,
       16.17857143, 16.5       , 14.86363636, 15.66666667, 16.44444444,
       16.125     , 15.25      , 17.09090909, 15.63636364, 18.7       ,
       18.63157895, 16.88888889, 15.125     , 15.7       , 15.375     ,
       14.66666667, 15.625     , 16.25      , 16.33333333, 16.875     ,
       17.57142857, 20.25      , 21.3       , 21.125     , 22.36363636,
       23.375     , 21.83333333, 19.125     , 18.625     , 19.125     ,
       19.        , 18.75      , 19.875     , 23.33333333, 24.46153846,
       23.75      , 20.5       , 19.125     , 19.75      , 20.        ,
       22.625     , 21.54545455, 20.78571429, 19.9375    , 18.53

In [131]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [132]:
mean_absolute_error(y_pred,pred)

8.917294569066609

In [135]:
mean_squared_error(y_pred,pred,squared=False)

10.461286597615553