In [1]:
import numpy as np
# import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from numpy.random import seed
seed(1)

In [3]:
dataset=pd.read_csv("Data/testset.csv")
dataset

datetime_utc          _conds  _dewptm  ...  _wgustm  _windchillm  _wspdm
0      19961101-11:00           Smoke      9.0  ...      NaN          NaN     7.4
1      19961101-12:00           Smoke     10.0  ...      NaN          NaN     NaN
2      19961101-13:00           Smoke     11.0  ...      NaN          NaN     NaN
3      19961101-14:00           Smoke     10.0  ...      NaN          NaN     NaN
4      19961101-16:00           Smoke     11.0  ...      NaN          NaN     0.0
...               ...             ...      ...  ...      ...          ...     ...
99565  20161231-12:00   Partly Cloudy     15.0  ...      NaN          NaN     7.4
99566  20161231-13:00   Partly Cloudy     16.0  ...      NaN          NaN     3.7
99567  20161231-15:00             NaN     13.0  ...      NaN          NaN    59.3
99568  20161231-18:00  Patches of Fog     12.0  ...      NaN          NaN     0.0
99569  20161231-21:00  Patches of Fog     12.0  ...      NaN          NaN     0.0

[99570 rows x 20 columns]

In [4]:
dataset.columns=dataset.columns.str.replace("_","")
dataset.columns=dataset.columns.str.replace(" ","")
dataset.columns

Index(['datetimeutc', 'conds', 'dewptm', 'fog', 'hail', 'heatindexm', 'hum',
       'precipm', 'pressurem', 'rain', 'snow', 'tempm', 'thunder', 'tornado',
       'vism', 'wdird', 'wdire', 'wgustm', 'windchillm', 'wspdm'],
      dtype='object')

In [5]:
dataset.drop(columns=["conds","dewptm","fog","hail","heatindexm","precipm","rain","snow","thunder","tornado","vism","wdird","wdire","wgustm","windchillm"],inplace=True,axis=1)
dataset

datetimeutc    hum  pressurem  tempm  wspdm
0      19961101-11:00   27.0     1010.0   30.0    7.4
1      19961101-12:00   32.0    -9999.0   28.0    NaN
2      19961101-13:00   44.0    -9999.0   24.0    NaN
3      19961101-14:00   41.0     1010.0   24.0    NaN
4      19961101-16:00   47.0     1011.0   23.0    0.0
...               ...    ...        ...    ...    ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4
99566  20161231-13:00  100.0     1014.0   16.0    3.7
99567  20161231-15:00    NaN     1016.0    NaN   59.3
99568  20161231-18:00  100.0     1016.0   12.0    0.0
99569  20161231-21:00   99.0     1016.0   12.0    0.0

[99570 rows x 5 columns]

In [6]:
dataset['pressurem'].replace('-9999.0',np.nan)
dataset.replace(0,np.nan)
dataset.isnull().sum()

datetimeutc       0
hum             756
pressurem       232
tempm           672
wspdm          2358
dtype: int64

In [7]:
dataset

datetimeutc    hum  pressurem  tempm  wspdm
0      19961101-11:00   27.0     1010.0   30.0    7.4
1      19961101-12:00   32.0    -9999.0   28.0    NaN
2      19961101-13:00   44.0    -9999.0   24.0    NaN
3      19961101-14:00   41.0     1010.0   24.0    NaN
4      19961101-16:00   47.0     1011.0   23.0    0.0
...               ...    ...        ...    ...    ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4
99566  20161231-13:00  100.0     1014.0   16.0    3.7
99567  20161231-15:00    NaN     1016.0    NaN   59.3
99568  20161231-18:00  100.0     1016.0   12.0    0.0
99569  20161231-21:00   99.0     1016.0   12.0    0.0

[99570 rows x 5 columns]

In [8]:
hum_median=dataset["hum"].median()
dataset["hum"].fillna(hum_median,inplace=True)
pressurem_median=dataset["pressurem"].median()
dataset["pressurem"].fillna(pressurem_median,inplace=True)
wspdm_median=dataset["wspdm"].median()
dataset["wspdm"].fillna(wspdm_median,inplace=True)
tempm_median=dataset["tempm"].median()
dataset["tempm"].fillna(tempm_median,inplace=True)

In [9]:
dataset.isnull().sum()

datetimeutc    0
hum            0
pressurem      0
tempm          0
wspdm          0
dtype: int64

In [10]:
dataset

datetimeutc    hum  pressurem  tempm  wspdm
0      19961101-11:00   27.0     1010.0   30.0    7.4
1      19961101-12:00   32.0    -9999.0   28.0    7.4
2      19961101-13:00   44.0    -9999.0   24.0    7.4
3      19961101-14:00   41.0     1010.0   24.0    7.4
4      19961101-16:00   47.0     1011.0   23.0    0.0
...               ...    ...        ...    ...    ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4
99566  20161231-13:00  100.0     1014.0   16.0    3.7
99567  20161231-15:00   58.0     1016.0   27.0   59.3
99568  20161231-18:00  100.0     1016.0   12.0    0.0
99569  20161231-21:00   99.0     1016.0   12.0    0.0

[99570 rows x 5 columns]

In [11]:
def extract_year(value):
    return (value[0:4])

In [12]:
def extract_month(value):
    return (value[4:6])

In [13]:
def extract_date(value):
    return (value[6:8])

In [14]:
dataset["year"]=dataset["datetimeutc"].apply(lambda x : extract_year(x))

In [15]:
dataset["month"]=dataset["datetimeutc"].apply(lambda x : extract_month(x))

In [16]:
dataset["date"]=dataset["datetimeutc"].apply(lambda x : extract_month(x))

In [17]:
dataset.year.value_counts()

2003    13186
2004     9151
2002     8503
2001     8403
2016     6634
1997     6513
1999     6300
2000     5391
1998     3579
2014     2973
2015     2936
2005     2920
2007     2865
2006     2858
2008     2857
2009     2851
2010     2768
2011     2738
2012     2438
2013     2428
1996     1278
Name: year, dtype: int64

In [18]:
dataset.groupby("year").tempm.mean()

year
1996    16.658059
1997    24.477199
1998    24.872031
1999    27.333333
2000    23.884252
2001    25.599667
2002    26.487005
2003    26.182239
2004    26.010054
2005    24.720548
2006    25.455213
2007    24.813264
2008    24.527476
2009    25.358821
2010    25.559610
2011    24.968590
2012    25.028712
2013    24.690692
2014    25.184326
2015    25.148161
2016    27.314591
Name: tempm, dtype: float64

In [19]:
dataset

datetimeutc    hum  pressurem  tempm  wspdm  year month date
0      19961101-11:00   27.0     1010.0   30.0    7.4  1996    11   11
1      19961101-12:00   32.0    -9999.0   28.0    7.4  1996    11   11
2      19961101-13:00   44.0    -9999.0   24.0    7.4  1996    11   11
3      19961101-14:00   41.0     1010.0   24.0    7.4  1996    11   11
4      19961101-16:00   47.0     1011.0   23.0    0.0  1996    11   11
...               ...    ...        ...    ...    ...   ...   ...  ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4  2016    12   12
99566  20161231-13:00  100.0     1014.0   16.0    3.7  2016    12   12
99567  20161231-15:00   58.0     1016.0   27.0   59.3  2016    12   12
99568  20161231-18:00  100.0     1016.0   12.0    0.0  2016    12   12
99569  20161231-21:00   99.0     1016.0   12.0    0.0  2016    12   12

[99570 rows x 8 columns]

In [20]:
dataset_forest=dataset[['hum','tempm','pressurem','wspdm','year','month','date']]

In [21]:
dataset_forest

hum  tempm  pressurem  wspdm  year month date
0       27.0   30.0     1010.0    7.4  1996    11   11
1       32.0   28.0    -9999.0    7.4  1996    11   11
2       44.0   24.0    -9999.0    7.4  1996    11   11
3       41.0   24.0     1010.0    7.4  1996    11   11
4       47.0   23.0     1011.0    0.0  1996    11   11
...      ...    ...        ...    ...   ...   ...  ...
99565   77.0   18.0     1015.0    7.4  2016    12   12
99566  100.0   16.0     1014.0    3.7  2016    12   12
99567   58.0   27.0     1016.0   59.3  2016    12   12
99568  100.0   12.0     1016.0    0.0  2016    12   12
99569   99.0   12.0     1016.0    0.0  2016    12   12

[99570 rows x 7 columns]

In [22]:
dataset_forest.dtypes

hum          float64
tempm        float64
pressurem    float64
wspdm        float64
year          object
month         object
date          object
dtype: object

In [23]:
y=dataset_forest["tempm"]
y

0        30.0
1        28.0
2        24.0
3        24.0
4        23.0
         ... 
99565    18.0
99566    16.0
99567    27.0
99568    12.0
99569    12.0
Name: tempm, Length: 99570, dtype: float64

In [24]:
dataset_forest.drop("tempm",inplace=True,axis=1)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4169: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [25]:
dataset_forest.columns

Index(['hum', 'pressurem', 'wspdm', 'year', 'month', 'date'], dtype='object')

In [26]:
X=dataset_forest.iloc[:,:].values


In [27]:
X.shape

(99570, 6)

In [28]:
y=y.values


In [29]:
y.shape

(99570,)

In [30]:
# Train and Test Part

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.10,random_state=0)

In [33]:
print("Shape of X_train", X_train.shape)
print("Shape of X_test", X_test.shape)
print("Shape of y_train", y_train.shape)
print("Shape of y_test", y_test.shape)

Shape of X_train (89613, 6)
Shape of X_test (9957, 6)
Shape of y_train (89613,)
Shape of y_test (9957,)


In [34]:
#Create Model
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor(random_state=0)

In [35]:
model.fit(X_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [36]:
y_pred=model.predict(X_test)

In [37]:
y_pred

array([31., 31., 13., ..., 27., 12., 25.])

In [38]:
y_test

array([32., 34., 16., ..., 32., 12., 25.])

In [39]:
# Accuracy
from sklearn.metrics import mean_squared_error, mean_absolute_error
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
print(f'{mse} {mae}')

7.913564634368969 1.8347824192028828


In [40]:
y_pred.size

9957

In [41]:
avg=0
for i in range(0,y_pred.size):
    avg+=abs(y_pred[i]-y_test[i])
avg

18268.928548003103

In [42]:
avg/(y_pred.size)

1.8347824192028828

In [43]:
df = pd.DataFrame({'Real Values':y_test.reshape(-1), 'Predicted Values':y_pred.reshape(-1)})
df

Real Values  Predicted Values
0            32.0              31.0
1            34.0              31.0
2            16.0              13.0
3            19.0              17.0
4            28.0              22.0
...           ...               ...
9952         27.0              23.0
9953         37.0              30.0
9954         32.0              27.0
9955         12.0              12.0
9956         25.0              25.0

[9957 rows x 2 columns]

In [44]:
from sklearn.metrics import mean_squared_error

In [45]:
mean_squared_error(y_test,y_pred)

7.913564634368969

In [46]:
mean_absolute_error(y_test,y_pred)

1.8347824192028828

In [47]:
y

array([30., 28., 24., ..., 27., 12., 12.])

In [48]:
y>50

array([False, False, False, ..., False, False, False])

In [49]:
d=y>50

In [50]:
d.size

99570

In [51]:
for i in range(0,d.size):
    if(d[i]==True):
        print("here")

here
here
here
here


In [52]:
test=pd.read_csv("archive/DailyDelhiClimateTest.csv")

In [53]:
test

date   meantemp   humidity  wind_speed  meanpressure
0    2017-01-01  15.913043  85.869565    2.743478     59.000000
1    2017-01-02  18.500000  77.222222    2.894444   1018.277778
2    2017-01-03  17.111111  81.888889    4.016667   1018.333333
3    2017-01-04  18.700000  70.050000    4.545000   1015.700000
4    2017-01-05  18.388889  74.944444    3.300000   1014.333333
..          ...        ...        ...         ...           ...
109  2017-04-20  34.500000  27.500000    5.562500    998.625000
110  2017-04-21  34.250000  39.375000    6.962500    999.875000
111  2017-04-22  32.900000  40.900000    8.890000   1001.600000
112  2017-04-23  32.875000  27.500000    9.962500   1002.125000
113  2017-04-24  32.000000  27.142857   12.157143   1004.142857

[114 rows x 5 columns]

In [54]:
def extract_year(value):
    return (value[0:4])

In [55]:
def extract_month(value):
    return (value[5:7])

In [56]:
def extract_date(value):
    return (value[8:10])

In [57]:
test["year"]=test["date"].apply(lambda x : extract_year(x))

In [58]:
test["month"]=test["date"].apply(lambda x : extract_month(x))

In [59]:
test["dat"]=test["date"].apply(lambda x : extract_date(x))

In [60]:
test

date   meantemp   humidity  wind_speed  meanpressure  year month dat
0    2017-01-01  15.913043  85.869565    2.743478     59.000000  2017    01  01
1    2017-01-02  18.500000  77.222222    2.894444   1018.277778  2017    01  02
2    2017-01-03  17.111111  81.888889    4.016667   1018.333333  2017    01  03
3    2017-01-04  18.700000  70.050000    4.545000   1015.700000  2017    01  04
4    2017-01-05  18.388889  74.944444    3.300000   1014.333333  2017    01  05
..          ...        ...        ...         ...           ...   ...   ...  ..
109  2017-04-20  34.500000  27.500000    5.562500    998.625000  2017    04  20
110  2017-04-21  34.250000  39.375000    6.962500    999.875000  2017    04  21
111  2017-04-22  32.900000  40.900000    8.890000   1001.600000  2017    04  22
112  2017-04-23  32.875000  27.500000    9.962500   1002.125000  2017    04  23
113  2017-04-24  32.000000  27.142857   12.157143   1004.142857  2017    04  24

[114 rows x 8 columns]

In [61]:
test.dtypes

date             object
meantemp        float64
humidity        float64
wind_speed      float64
meanpressure    float64
year             object
month            object
dat              object
dtype: object

In [62]:
pred=test['meantemp']
pred

0      15.913043
1      18.500000
2      17.111111
3      18.700000
4      18.388889
         ...    
109    34.500000
110    34.250000
111    32.900000
112    32.875000
113    32.000000
Name: meantemp, Length: 114, dtype: float64

In [63]:
test.drop('meantemp',inplace=True,axis=1)
test.drop('date',inplace=True,axis=1)
# test.drop('meanpressure',inplace=True,axis=1)
test

humidity  wind_speed  meanpressure  year month dat
0    85.869565    2.743478     59.000000  2017    01  01
1    77.222222    2.894444   1018.277778  2017    01  02
2    81.888889    4.016667   1018.333333  2017    01  03
3    70.050000    4.545000   1015.700000  2017    01  04
4    74.944444    3.300000   1014.333333  2017    01  05
..         ...         ...           ...   ...   ...  ..
109  27.500000    5.562500    998.625000  2017    04  20
110  39.375000    6.962500    999.875000  2017    04  21
111  40.900000    8.890000   1001.600000  2017    04  22
112  27.500000    9.962500   1002.125000  2017    04  23
113  27.142857   12.157143   1004.142857  2017    04  24

[114 rows x 6 columns]

In [64]:
X=test.iloc[:,:].values
X.shape

(114, 6)

In [65]:
pred=pred.values
pred.shape

(114,)

In [66]:
y_pred=model.predict(X)

In [67]:
y_pred

array([13., 22., 19., 21., 23., 20., 19., 18., 22., 22., 22., 23., 18.,
       21., 18., 21., 18., 21., 23., 18., 22., 23., 23., 18., 21., 21.,
       21., 18., 19., 21., 23., 22., 19., 21., 21., 21., 21., 22., 18.,
       18., 22., 22., 21., 18., 22., 18., 21., 22., 22., 18., 22., 21.,
       21., 36., 38., 36., 22., 34., 28., 15., 26., 33., 33., 36., 36.,
       36., 21., 21., 18., 22., 21., 36., 21., 23., 36., 22., 36., 28.,
       23., 36., 36., 36., 35., 35., 35., 35., 36., 35., 35., 35., 20.,
       20., 39., 39., 36., 39., 39., 39., 38., 38., 38., 39., 39., 35.,
       39., 35., 35., 39., 41., 39., 35., 36., 39., 39.])

In [68]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [69]:
mean_absolute_error(y_pred,pred)

6.115616967535153