In [1]:
import numpy as np
# import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from numpy.random import seed
seed(1)

In [3]:
dataset=pd.read_csv("Data/testset.csv")
dataset

datetime_utc          _conds  _dewptm  ...  _wgustm  _windchillm  _wspdm
0      19961101-11:00           Smoke      9.0  ...      NaN          NaN     7.4
1      19961101-12:00           Smoke     10.0  ...      NaN          NaN     NaN
2      19961101-13:00           Smoke     11.0  ...      NaN          NaN     NaN
3      19961101-14:00           Smoke     10.0  ...      NaN          NaN     NaN
4      19961101-16:00           Smoke     11.0  ...      NaN          NaN     0.0
...               ...             ...      ...  ...      ...          ...     ...
99565  20161231-12:00   Partly Cloudy     15.0  ...      NaN          NaN     7.4
99566  20161231-13:00   Partly Cloudy     16.0  ...      NaN          NaN     3.7
99567  20161231-15:00             NaN     13.0  ...      NaN          NaN    59.3
99568  20161231-18:00  Patches of Fog     12.0  ...      NaN          NaN     0.0
99569  20161231-21:00  Patches of Fog     12.0  ...      NaN          NaN     0.0

[99570 rows x 20 columns]

In [4]:
dataset.columns=dataset.columns.str.replace("_","")
dataset.columns=dataset.columns.str.replace(" ","")
dataset.columns

Index(['datetimeutc', 'conds', 'dewptm', 'fog', 'hail', 'heatindexm', 'hum',
       'precipm', 'pressurem', 'rain', 'snow', 'tempm', 'thunder', 'tornado',
       'vism', 'wdird', 'wdire', 'wgustm', 'windchillm', 'wspdm'],
      dtype='object')

In [5]:
dataset.drop(columns=["conds","dewptm","fog","hail","heatindexm","precipm","rain","snow","thunder","tornado","vism","wdird","wdire","wgustm","windchillm"],inplace=True,axis=1)
dataset

datetimeutc    hum  pressurem  tempm  wspdm
0      19961101-11:00   27.0     1010.0   30.0    7.4
1      19961101-12:00   32.0    -9999.0   28.0    NaN
2      19961101-13:00   44.0    -9999.0   24.0    NaN
3      19961101-14:00   41.0     1010.0   24.0    NaN
4      19961101-16:00   47.0     1011.0   23.0    0.0
...               ...    ...        ...    ...    ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4
99566  20161231-13:00  100.0     1014.0   16.0    3.7
99567  20161231-15:00    NaN     1016.0    NaN   59.3
99568  20161231-18:00  100.0     1016.0   12.0    0.0
99569  20161231-21:00   99.0     1016.0   12.0    0.0

[99570 rows x 5 columns]

In [6]:
dataset['pressurem'].replace('-9999.0',np.nan)
dataset.replace(0,np.nan)
dataset.isnull().sum()

datetimeutc       0
hum             756
pressurem       232
tempm           672
wspdm          2358
dtype: int64

In [7]:
dataset

datetimeutc    hum  pressurem  tempm  wspdm
0      19961101-11:00   27.0     1010.0   30.0    7.4
1      19961101-12:00   32.0    -9999.0   28.0    NaN
2      19961101-13:00   44.0    -9999.0   24.0    NaN
3      19961101-14:00   41.0     1010.0   24.0    NaN
4      19961101-16:00   47.0     1011.0   23.0    0.0
...               ...    ...        ...    ...    ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4
99566  20161231-13:00  100.0     1014.0   16.0    3.7
99567  20161231-15:00    NaN     1016.0    NaN   59.3
99568  20161231-18:00  100.0     1016.0   12.0    0.0
99569  20161231-21:00   99.0     1016.0   12.0    0.0

[99570 rows x 5 columns]

In [8]:
hum_median=dataset["hum"].median()
dataset["hum"].fillna(hum_median,inplace=True)
pressurem_median=dataset["pressurem"].median()
dataset["pressurem"].fillna(pressurem_median,inplace=True)
wspdm_median=dataset["wspdm"].median()
dataset["wspdm"].fillna(wspdm_median,inplace=True)
tempm_median=dataset["tempm"].median()
dataset["tempm"].fillna(tempm_median,inplace=True)

In [9]:
dataset.isnull().sum()

datetimeutc    0
hum            0
pressurem      0
tempm          0
wspdm          0
dtype: int64

In [10]:
dataset

datetimeutc    hum  pressurem  tempm  wspdm
0      19961101-11:00   27.0     1010.0   30.0    7.4
1      19961101-12:00   32.0    -9999.0   28.0    7.4
2      19961101-13:00   44.0    -9999.0   24.0    7.4
3      19961101-14:00   41.0     1010.0   24.0    7.4
4      19961101-16:00   47.0     1011.0   23.0    0.0
...               ...    ...        ...    ...    ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4
99566  20161231-13:00  100.0     1014.0   16.0    3.7
99567  20161231-15:00   58.0     1016.0   27.0   59.3
99568  20161231-18:00  100.0     1016.0   12.0    0.0
99569  20161231-21:00   99.0     1016.0   12.0    0.0

[99570 rows x 5 columns]

In [11]:
dataset["datetimeutc"]=pd.to_datetime(dataset["datetimeutc"])

In [12]:
dataset.set_index("datetimeutc",inplace=True)

In [13]:
dataset

hum  pressurem  tempm  wspdm
datetimeutc                                        
1996-11-01 11:00:00   27.0     1010.0   30.0    7.4
1996-11-01 12:00:00   32.0    -9999.0   28.0    7.4
1996-11-01 13:00:00   44.0    -9999.0   24.0    7.4
1996-11-01 14:00:00   41.0     1010.0   24.0    7.4
1996-11-01 16:00:00   47.0     1011.0   23.0    0.0
...                    ...        ...    ...    ...
2016-12-31 12:00:00   77.0     1015.0   18.0    7.4
2016-12-31 13:00:00  100.0     1014.0   16.0    3.7
2016-12-31 15:00:00   58.0     1016.0   27.0   59.3
2016-12-31 18:00:00  100.0     1016.0   12.0    0.0
2016-12-31 21:00:00   99.0     1016.0   12.0    0.0

[99570 rows x 4 columns]

In [14]:
dataset=dataset.resample("D").mean()
dataset

hum    pressurem      tempm      wspdm
datetimeutc                                              
1996-11-01   52.916667 -2659.666667  22.333333   6.166667
1996-11-02   48.625000  1009.833333  22.916667   7.950000
1996-11-03   55.958333  1010.500000  21.791667   5.020833
1996-11-04   48.055556  1011.333333  22.722222   2.266667
1996-11-05   29.400000  1011.800000  27.800000  10.020000
...                ...          ...        ...        ...
2016-12-27   67.550000  1017.200000  16.850000   8.335000
2016-12-28   68.043478  1015.565217  17.217391   3.547826
2016-12-29   87.857143  1016.904762  15.238095   6.000000
2016-12-30   89.666667  1017.904762  14.095238   6.266667
2016-12-31   85.550000  1016.100000  15.650000   7.325000

[7366 rows x 4 columns]

In [15]:
def extract_year(value):
  value=value.strftime('%Y-%m-%d')
  return (value[0:4])


def extract_month(value):
    value=value.strftime('%Y-%m-%d')
    return (value[4:6])

def extract_date(value):
    value=value.strftime('%Y-%m-%d')
    return (value[6:8])

In [16]:
dataset.reset_index(inplace=True)
dataset


datetimeutc        hum    pressurem      tempm      wspdm
0     1996-11-01  52.916667 -2659.666667  22.333333   6.166667
1     1996-11-02  48.625000  1009.833333  22.916667   7.950000
2     1996-11-03  55.958333  1010.500000  21.791667   5.020833
3     1996-11-04  48.055556  1011.333333  22.722222   2.266667
4     1996-11-05  29.400000  1011.800000  27.800000  10.020000
...          ...        ...          ...        ...        ...
7361  2016-12-27  67.550000  1017.200000  16.850000   8.335000
7362  2016-12-28  68.043478  1015.565217  17.217391   3.547826
7363  2016-12-29  87.857143  1016.904762  15.238095   6.000000
7364  2016-12-30  89.666667  1017.904762  14.095238   6.266667
7365  2016-12-31  85.550000  1016.100000  15.650000   7.325000

[7366 rows x 5 columns]

In [17]:
dataset['day'] = dataset['datetimeutc'].dt.day
dataset['month'] = dataset['datetimeutc'].dt.month
dataset['year'] = dataset['datetimeutc'].dt.year

In [18]:
dataset.isnull().sum()

datetimeutc      0
hum            141
pressurem      141
tempm          141
wspdm          141
day              0
month            0
year             0
dtype: int64

In [19]:
dataset.fillna(dataset.mean(),inplace=True)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  """Entry point for launching an IPython kernel.


In [20]:
dataset.isnull().sum()

datetimeutc    0
hum            0
pressurem      0
tempm          0
wspdm          0
day            0
month          0
year           0
dtype: int64

In [21]:
dataset_svr=dataset.drop(["datetimeutc"],axis=1)
dataset_svr

hum    pressurem      tempm      wspdm  day  month  year
0     52.916667 -2659.666667  22.333333   6.166667    1     11  1996
1     48.625000  1009.833333  22.916667   7.950000    2     11  1996
2     55.958333  1010.500000  21.791667   5.020833    3     11  1996
3     48.055556  1011.333333  22.722222   2.266667    4     11  1996
4     29.400000  1011.800000  27.800000  10.020000    5     11  1996
...         ...          ...        ...        ...  ...    ...   ...
7361  67.550000  1017.200000  16.850000   8.335000   27     12  2016
7362  68.043478  1015.565217  17.217391   3.547826   28     12  2016
7363  87.857143  1016.904762  15.238095   6.000000   29     12  2016
7364  89.666667  1017.904762  14.095238   6.266667   30     12  2016
7365  85.550000  1016.100000  15.650000   7.325000   31     12  2016

[7366 rows x 7 columns]

In [22]:
y=dataset_svr["tempm"]
y

0       22.333333
1       22.916667
2       21.791667
3       22.722222
4       27.800000
          ...    
7361    16.850000
7362    17.217391
7363    15.238095
7364    14.095238
7365    15.650000
Name: tempm, Length: 7366, dtype: float64

In [23]:
dataset_svr.drop("tempm",inplace=True,axis=1)

In [24]:
dataset_svr.columns

Index(['hum', 'pressurem', 'wspdm', 'day', 'month', 'year'], dtype='object')

In [25]:
X=dataset_svr.iloc[:,:].values
X.shape

(7366, 6)

In [26]:
y=y.values
y.shape

(7366,)

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=0)

In [29]:
print("Shape of X_train", X_train.shape)
print("Shape of X_test", X_test.shape)
print("Shape of y_train", y_train.shape)
print("Shape of y_test", y_test.shape)

Shape of X_train (4935, 6)
Shape of X_test (2431, 6)
Shape of y_train (4935,)
Shape of y_test (2431,)


In [30]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
sc_Y=StandardScaler()
X_train=sc_X.fit_transform(X_train)
y_train=np.array(y_train).reshape(-1,1)
y_train=sc_Y.fit_transform(y_train)
# y_train=np.array(y_train).reshape(-1,1)

In [31]:
from sklearn.svm import SVR

In [32]:
regressor = SVR(kernel = 'rbf')

In [33]:
regressor.fit(X_train,y_train.ravel())

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [34]:
X_test=sc_X.fit_transform(X_test)
y_pred=regressor.predict(X_test)

In [35]:
y_pred=sc_Y.inverse_transform(y_pred)
y_pred

array([28.86631792, 33.19620759, 20.17374287, ..., 14.63009079,
       32.95245274, 15.7592242 ])

In [36]:
y_test

array([28.875     , 32.5       , 24.75      , ..., 19.52173913,
       32.875     , 14.71428571])

In [37]:
# Accuracy
from sklearn.metrics import mean_squared_error, mean_absolute_error
mse=mean_squared_error(y_test,y_pred,squared=False)
mae=mean_absolute_error(y_test,y_pred)
print(f'{mse} {mae}')

2.016785599986925 1.5070164620845157


In [39]:
test=pd.read_csv("archive/DailyDelhiClimateTest.csv")

In [40]:
test

date   meantemp   humidity  wind_speed  meanpressure
0    2017-01-01  15.913043  85.869565    2.743478     59.000000
1    2017-01-02  18.500000  77.222222    2.894444   1018.277778
2    2017-01-03  17.111111  81.888889    4.016667   1018.333333
3    2017-01-04  18.700000  70.050000    4.545000   1015.700000
4    2017-01-05  18.388889  74.944444    3.300000   1014.333333
..          ...        ...        ...         ...           ...
109  2017-04-20  34.500000  27.500000    5.562500    998.625000
110  2017-04-21  34.250000  39.375000    6.962500    999.875000
111  2017-04-22  32.900000  40.900000    8.890000   1001.600000
112  2017-04-23  32.875000  27.500000    9.962500   1002.125000
113  2017-04-24  32.000000  27.142857   12.157143   1004.142857

[114 rows x 5 columns]

In [41]:
def extract_year(value):
    return (value[0:4])

def extract_month(value):
    return (value[5:7])

def extract_date(value):
    return (value[8:10])

In [42]:
test["year"]=test["date"].apply(lambda x : extract_year(x))
test["month"]=test["date"].apply(lambda x : extract_month(x))
test["dat"]=test["date"].apply(lambda x : extract_date(x))
test

date   meantemp   humidity  wind_speed  meanpressure  year month dat
0    2017-01-01  15.913043  85.869565    2.743478     59.000000  2017    01  01
1    2017-01-02  18.500000  77.222222    2.894444   1018.277778  2017    01  02
2    2017-01-03  17.111111  81.888889    4.016667   1018.333333  2017    01  03
3    2017-01-04  18.700000  70.050000    4.545000   1015.700000  2017    01  04
4    2017-01-05  18.388889  74.944444    3.300000   1014.333333  2017    01  05
..          ...        ...        ...         ...           ...   ...   ...  ..
109  2017-04-20  34.500000  27.500000    5.562500    998.625000  2017    04  20
110  2017-04-21  34.250000  39.375000    6.962500    999.875000  2017    04  21
111  2017-04-22  32.900000  40.900000    8.890000   1001.600000  2017    04  22
112  2017-04-23  32.875000  27.500000    9.962500   1002.125000  2017    04  23
113  2017-04-24  32.000000  27.142857   12.157143   1004.142857  2017    04  24

[114 rows x 8 columns]

In [43]:
pred=test['meantemp']
pred

0      15.913043
1      18.500000
2      17.111111
3      18.700000
4      18.388889
         ...    
109    34.500000
110    34.250000
111    32.900000
112    32.875000
113    32.000000
Name: meantemp, Length: 114, dtype: float64

In [44]:
test.drop('meantemp',inplace=True,axis=1)
test.drop('date',inplace=True,axis=1)
# test.drop('meanpressure',inplace=True,axis=1)
test

humidity  wind_speed  meanpressure  year month dat
0    85.869565    2.743478     59.000000  2017    01  01
1    77.222222    2.894444   1018.277778  2017    01  02
2    81.888889    4.016667   1018.333333  2017    01  03
3    70.050000    4.545000   1015.700000  2017    01  04
4    74.944444    3.300000   1014.333333  2017    01  05
..         ...         ...           ...   ...   ...  ..
109  27.500000    5.562500    998.625000  2017    04  20
110  39.375000    6.962500    999.875000  2017    04  21
111  40.900000    8.890000   1001.600000  2017    04  22
112  27.500000    9.962500   1002.125000  2017    04  23
113  27.142857   12.157143   1004.142857  2017    04  24

[114 rows x 6 columns]

In [45]:
X=test.iloc[:,:].values
X.shape

(114, 6)

In [46]:
X=sc_X.fit_transform(X)

In [47]:
pred=pred.values
pred.shape

(114,)

In [49]:
y_pred=regressor.predict(X)

In [50]:
y_pred=sc_Y.inverse_transform(y_pred)
y_pred

array([19.93187808, 15.99338063, 15.43476301, 16.42453419, 16.07561907,
       15.55521515, 13.55753815, 15.57567961, 15.69960831, 17.11521052,
       17.13391278, 16.9227209 , 18.00583422, 17.24473585, 17.55408674,
       16.04550744, 15.66616843, 17.06309344, 16.28892549, 16.72335346,
       17.08373219, 17.6066022 , 17.27891333, 19.41319233, 16.85635854,
       15.56150737, 16.81176666, 16.00195278, 16.09567806, 19.55482883,
       19.87624424, 28.20553829, 29.31316961, 28.00197263, 26.85178973,
       27.4534886 , 28.51102674, 29.91939141, 28.8789157 , 28.91498178,
       27.78965683, 29.51718451, 27.90918603, 29.09499979, 29.30358128,
       28.88370088, 28.91130288, 28.47277425, 28.24550774, 29.24110874,
       30.234463  , 25.63886214, 30.65641209, 26.07028291, 24.99226099,
       28.03414218, 28.19454293, 31.86505609, 33.03329123, 32.16099763,
       32.2058083 , 33.07182537, 33.02558616, 32.27817218, 32.43345437,
       33.76554488, 31.44596604, 30.84400062, 29.11936769, 31.94

In [51]:
pred

array([15.91304348, 18.5       , 17.11111111, 18.7       , 18.38888889,
       19.31818182, 14.70833333, 15.68421053, 14.57142857, 12.11111111,
       11.        , 11.78947368, 13.23529412, 13.2       , 16.43478261,
       14.65      , 11.72222222, 13.04166667, 14.61904762, 15.26315789,
       15.39130435, 18.44      , 18.11764706, 18.34782609, 21.        ,
       16.17857143, 16.5       , 14.86363636, 15.66666667, 16.44444444,
       16.125     , 15.25      , 17.09090909, 15.63636364, 18.7       ,
       18.63157895, 16.88888889, 15.125     , 15.7       , 15.375     ,
       14.66666667, 15.625     , 16.25      , 16.33333333, 16.875     ,
       17.57142857, 20.25      , 21.3       , 21.125     , 22.36363636,
       23.375     , 21.83333333, 19.125     , 18.625     , 19.125     ,
       19.        , 18.75      , 19.875     , 23.33333333, 24.46153846,
       23.75      , 20.5       , 19.125     , 19.75      , 20.        ,
       22.625     , 21.54545455, 20.78571429, 19.9375    , 18.53

In [52]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [53]:
mean_absolute_error(y_pred,pred)

7.989914055897153

In [54]:
mean_squared_error(y_pred,pred,squared=False)

9.33057093828051