<a href="https://colab.research.google.com/github/shitizz24/Time-Series-Forecasting/blob/master/Support_Vector_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np
# import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

In [58]:
from numpy.random import seed
seed(1)

In [59]:
dataset=pd.read_csv("Data/testset.csv")
dataset

datetime_utc          _conds  _dewptm  ...  _wgustm  _windchillm  _wspdm
0      19961101-11:00           Smoke      9.0  ...      NaN          NaN     7.4
1      19961101-12:00           Smoke     10.0  ...      NaN          NaN     NaN
2      19961101-13:00           Smoke     11.0  ...      NaN          NaN     NaN
3      19961101-14:00           Smoke     10.0  ...      NaN          NaN     NaN
4      19961101-16:00           Smoke     11.0  ...      NaN          NaN     0.0
...               ...             ...      ...  ...      ...          ...     ...
99565  20161231-12:00   Partly Cloudy     15.0  ...      NaN          NaN     7.4
99566  20161231-13:00   Partly Cloudy     16.0  ...      NaN          NaN     3.7
99567  20161231-15:00             NaN     13.0  ...      NaN          NaN    59.3
99568  20161231-18:00  Patches of Fog     12.0  ...      NaN          NaN     0.0
99569  20161231-21:00  Patches of Fog     12.0  ...      NaN          NaN     0.0

[99570 rows x 20 columns]

In [60]:
dataset.columns=dataset.columns.str.replace("_","")
dataset.columns=dataset.columns.str.replace(" ","")
dataset.columns

Index(['datetimeutc', 'conds', 'dewptm', 'fog', 'hail', 'heatindexm', 'hum',
       'precipm', 'pressurem', 'rain', 'snow', 'tempm', 'thunder', 'tornado',
       'vism', 'wdird', 'wdire', 'wgustm', 'windchillm', 'wspdm'],
      dtype='object')

In [61]:
dataset.drop(columns=["conds","dewptm","fog","hail","heatindexm","precipm","rain","snow","thunder","tornado","vism","wdird","wdire","wgustm","windchillm"],inplace=True,axis=1)
dataset

datetimeutc    hum  pressurem  tempm  wspdm
0      19961101-11:00   27.0     1010.0   30.0    7.4
1      19961101-12:00   32.0    -9999.0   28.0    NaN
2      19961101-13:00   44.0    -9999.0   24.0    NaN
3      19961101-14:00   41.0     1010.0   24.0    NaN
4      19961101-16:00   47.0     1011.0   23.0    0.0
...               ...    ...        ...    ...    ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4
99566  20161231-13:00  100.0     1014.0   16.0    3.7
99567  20161231-15:00    NaN     1016.0    NaN   59.3
99568  20161231-18:00  100.0     1016.0   12.0    0.0
99569  20161231-21:00   99.0     1016.0   12.0    0.0

[99570 rows x 5 columns]

In [62]:
dataset['pressurem'].replace('-9999.0',np.nan)
dataset.replace(0,np.nan)
dataset.isnull().sum()

datetimeutc       0
hum             756
pressurem       232
tempm           672
wspdm          2358
dtype: int64

In [63]:
dataset

datetimeutc    hum  pressurem  tempm  wspdm
0      19961101-11:00   27.0     1010.0   30.0    7.4
1      19961101-12:00   32.0    -9999.0   28.0    NaN
2      19961101-13:00   44.0    -9999.0   24.0    NaN
3      19961101-14:00   41.0     1010.0   24.0    NaN
4      19961101-16:00   47.0     1011.0   23.0    0.0
...               ...    ...        ...    ...    ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4
99566  20161231-13:00  100.0     1014.0   16.0    3.7
99567  20161231-15:00    NaN     1016.0    NaN   59.3
99568  20161231-18:00  100.0     1016.0   12.0    0.0
99569  20161231-21:00   99.0     1016.0   12.0    0.0

[99570 rows x 5 columns]

In [64]:
hum_median=dataset["hum"].median()
dataset["hum"].fillna(hum_median,inplace=True)
pressurem_median=dataset["pressurem"].median()
dataset["pressurem"].fillna(pressurem_median,inplace=True)
wspdm_median=dataset["wspdm"].median()
dataset["wspdm"].fillna(wspdm_median,inplace=True)
tempm_median=dataset["tempm"].median()
dataset["tempm"].fillna(tempm_median,inplace=True)

In [65]:
dataset.isnull().sum()

datetimeutc    0
hum            0
pressurem      0
tempm          0
wspdm          0
dtype: int64

In [66]:
dataset

datetimeutc    hum  pressurem  tempm  wspdm
0      19961101-11:00   27.0     1010.0   30.0    7.4
1      19961101-12:00   32.0    -9999.0   28.0    7.4
2      19961101-13:00   44.0    -9999.0   24.0    7.4
3      19961101-14:00   41.0     1010.0   24.0    7.4
4      19961101-16:00   47.0     1011.0   23.0    0.0
...               ...    ...        ...    ...    ...
99565  20161231-12:00   77.0     1015.0   18.0    7.4
99566  20161231-13:00  100.0     1014.0   16.0    3.7
99567  20161231-15:00   58.0     1016.0   27.0   59.3
99568  20161231-18:00  100.0     1016.0   12.0    0.0
99569  20161231-21:00   99.0     1016.0   12.0    0.0

[99570 rows x 5 columns]

In [67]:
dataset["datetimeutc"]=pd.to_datetime(dataset["datetimeutc"])

In [68]:
dataset.set_index("datetimeutc",inplace=True)

In [69]:
dataset

hum  pressurem  tempm  wspdm
datetimeutc                                        
1996-11-01 11:00:00   27.0     1010.0   30.0    7.4
1996-11-01 12:00:00   32.0    -9999.0   28.0    7.4
1996-11-01 13:00:00   44.0    -9999.0   24.0    7.4
1996-11-01 14:00:00   41.0     1010.0   24.0    7.4
1996-11-01 16:00:00   47.0     1011.0   23.0    0.0
...                    ...        ...    ...    ...
2016-12-31 12:00:00   77.0     1015.0   18.0    7.4
2016-12-31 13:00:00  100.0     1014.0   16.0    3.7
2016-12-31 15:00:00   58.0     1016.0   27.0   59.3
2016-12-31 18:00:00  100.0     1016.0   12.0    0.0
2016-12-31 21:00:00   99.0     1016.0   12.0    0.0

[99570 rows x 4 columns]

In [70]:
dataset=dataset.resample("D").mean()
dataset

hum    pressurem      tempm      wspdm
datetimeutc                                              
1996-11-01   52.916667 -2659.666667  22.333333   6.166667
1996-11-02   48.625000  1009.833333  22.916667   7.950000
1996-11-03   55.958333  1010.500000  21.791667   5.020833
1996-11-04   48.055556  1011.333333  22.722222   2.266667
1996-11-05   29.400000  1011.800000  27.800000  10.020000
...                ...          ...        ...        ...
2016-12-27   67.550000  1017.200000  16.850000   8.335000
2016-12-28   68.043478  1015.565217  17.217391   3.547826
2016-12-29   87.857143  1016.904762  15.238095   6.000000
2016-12-30   89.666667  1017.904762  14.095238   6.266667
2016-12-31   85.550000  1016.100000  15.650000   7.325000

[7366 rows x 4 columns]

In [71]:
def extract_year(value):
  value=value.strftime('%Y-%m-%d')
  return (value[0:4])


def extract_month(value):
    value=value.strftime('%Y-%m-%d')
    return (value[4:6])

def extract_date(value):
    value=value.strftime('%Y-%m-%d')
    return (value[6:8])

In [72]:
dataset.reset_index(inplace=True)
dataset


datetimeutc        hum    pressurem      tempm      wspdm
0     1996-11-01  52.916667 -2659.666667  22.333333   6.166667
1     1996-11-02  48.625000  1009.833333  22.916667   7.950000
2     1996-11-03  55.958333  1010.500000  21.791667   5.020833
3     1996-11-04  48.055556  1011.333333  22.722222   2.266667
4     1996-11-05  29.400000  1011.800000  27.800000  10.020000
...          ...        ...          ...        ...        ...
7361  2016-12-27  67.550000  1017.200000  16.850000   8.335000
7362  2016-12-28  68.043478  1015.565217  17.217391   3.547826
7363  2016-12-29  87.857143  1016.904762  15.238095   6.000000
7364  2016-12-30  89.666667  1017.904762  14.095238   6.266667
7365  2016-12-31  85.550000  1016.100000  15.650000   7.325000

[7366 rows x 5 columns]

In [73]:
dataset['day'] = dataset['datetimeutc'].dt.day
dataset['month'] = dataset['datetimeutc'].dt.month
dataset['year'] = dataset['datetimeutc'].dt.year

In [74]:
dataset.isnull().sum()

datetimeutc      0
hum            141
pressurem      141
tempm          141
wspdm          141
day              0
month            0
year             0
dtype: int64

In [75]:
dataset.fillna(dataset.mean(),inplace=True)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  """Entry point for launching an IPython kernel.


In [76]:
dataset.isnull().sum()

datetimeutc    0
hum            0
pressurem      0
tempm          0
wspdm          0
day            0
month          0
year           0
dtype: int64

In [77]:
dataset_svr=dataset.drop(["datetimeutc"],axis=1)
dataset_svr

hum    pressurem      tempm      wspdm  day  month  year
0     52.916667 -2659.666667  22.333333   6.166667    1     11  1996
1     48.625000  1009.833333  22.916667   7.950000    2     11  1996
2     55.958333  1010.500000  21.791667   5.020833    3     11  1996
3     48.055556  1011.333333  22.722222   2.266667    4     11  1996
4     29.400000  1011.800000  27.800000  10.020000    5     11  1996
...         ...          ...        ...        ...  ...    ...   ...
7361  67.550000  1017.200000  16.850000   8.335000   27     12  2016
7362  68.043478  1015.565217  17.217391   3.547826   28     12  2016
7363  87.857143  1016.904762  15.238095   6.000000   29     12  2016
7364  89.666667  1017.904762  14.095238   6.266667   30     12  2016
7365  85.550000  1016.100000  15.650000   7.325000   31     12  2016

[7366 rows x 7 columns]

In [78]:
y=dataset_svr["tempm"]
y

0       22.333333
1       22.916667
2       21.791667
3       22.722222
4       27.800000
          ...    
7361    16.850000
7362    17.217391
7363    15.238095
7364    14.095238
7365    15.650000
Name: tempm, Length: 7366, dtype: float64

In [79]:
dataset_svr.drop("tempm",inplace=True,axis=1)

In [80]:
dataset_svr.columns

Index(['hum', 'pressurem', 'wspdm', 'day', 'month', 'year'], dtype='object')

In [81]:
X=dataset_svr.iloc[:,:].values
X.shape

(7366, 6)

In [82]:
y=y.values
y.shape

(7366,)

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=0)

In [85]:
print("Shape of X_train", X_train.shape)
print("Shape of X_test", X_test.shape)
print("Shape of y_train", y_train.shape)
print("Shape of y_test", y_test.shape)

Shape of X_train (4935, 6)
Shape of X_test (2431, 6)
Shape of y_train (4935,)
Shape of y_test (2431,)


In [86]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
sc_Y=StandardScaler()
X_train=sc_X.fit_transform(X_train)
y_train=np.array(y_train).reshape(-1,1)
y_train=sc_Y.fit_transform(y_train)
# y_train=np.array(y_train).reshape(-1,1)

array([[ 5.29166667e+01, -2.65966667e+03,  6.16666667e+00,
         1.00000000e+00,  1.10000000e+01,  1.99600000e+03],
       [ 4.86250000e+01,  1.00983333e+03,  7.95000000e+00,
         2.00000000e+00,  1.10000000e+01,  1.99600000e+03],
       [ 5.59583333e+01,  1.01050000e+03,  5.02083333e+00,
         3.00000000e+00,  1.10000000e+01,  1.99600000e+03],
       ...,
       [ 8.78571429e+01,  1.01690476e+03,  6.00000000e+00,
         2.90000000e+01,  1.20000000e+01,  2.01600000e+03],
       [ 8.96666667e+01,  1.01790476e+03,  6.26666667e+00,
         3.00000000e+01,  1.20000000e+01,  2.01600000e+03],
       [ 8.55500000e+01,  1.01610000e+03,  7.32500000e+00,
         3.10000000e+01,  1.20000000e+01,  2.01600000e+03]])

In [87]:
from sklearn.svm import SVR

In [88]:
regressor = SVR(kernel = 'rbf')

In [89]:
regressor.fit(X_train,y_train.ravel())

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [90]:
X_test=sc_X.fit_transform(X_test)
y_pred=regressor.predict(X_test)

In [91]:
y_pred=sc_Y.inverse_transform(y_pred)
y_pred

array([28.86631792, 33.19620759, 20.17374287, ..., 14.63009079,
       32.95245274, 15.7592242 ])

In [92]:
y_test

array([28.875     , 32.5       , 24.75      , ..., 19.52173913,
       32.875     , 14.71428571])

In [93]:
# Accuracy
from sklearn.metrics import mean_squared_error, mean_absolute_error
mse=mean_squared_error(y_test,y_pred,squared='false')
mae=mean_absolute_error(y_test,y_pred)
print(f'{mse} {mae}')

4.067424156314621 1.5070164620845157
